//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfBankingService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Statement
    {
        public int ID { get; set; }
        public string IBANFrom { get; set; }
        public string IBANTo { get; set; }
        public Nullable<decimal> FullMoney { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Withdraw { get; set; }
        public string Channel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Req_No { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
